Made MFA optional

diff --git a/assumerole b/assumerole
--- a/assumerole
+++ b/assumerole
@@ -69,19 +69,22 @@ ASSUMEROLE_ENV=$(jq -j --raw-output ".assume_roles[\"${aws_account}\"] | select(
 CreateCredentials() {
   ### Check config before asking for the MFA token
   GetAccountInfo
+  local use_mfa="true"
 
   [[ "${PROFILE}" = "null" ]] && { echo "aws_profile missing for account ${aws_account} in ${CONF}"; exit 1; }
   [[ "${ACCOUNT}" = "null" ]] && { echo "aws_account missing for account ${aws_account} in ${CONF}"; exit 1; }
   [[ "${ROLE}" = "null" ]]    && { echo "aws_role missing for account ${aws_account} in ${CONF}"; exit 1; }
-  [[ "${MFA_ARN}" = "null" ]] && { echo "aws_mfa_arn missing for account ${aws_account} in ${CONF}"; exit 1; }
+  [[ "${MFA_ARN}" = "null" ]] && { echo "aws_mfa_arn missing for account ${aws_account} in ${CONF}"; use_mfa="false"; }
 
   ### Get MFA token from commandline or ask for it
-  if [[ -n ${2} ]]
-  then
-    aws_token=${2}
-  else
-    printf "MFA token: "
-    read aws_token
+  if [[ "${use_mfa}" = "true" ]]; then
+    if [[ -n ${2} ]]
+    then
+      aws_token=${2}
+    else
+      printf "MFA token: "
+      read aws_token
+    fi
   fi
 
   unset AWS_ACCESS_KEY_ID
@@ -91,12 +94,20 @@ CreateCredentials() {
 
   export AWS_PROFILE=${PROFILE}
 
-  JSON=$(aws sts assume-role \
-           --role-arn arn:aws:iam::${ACCOUNT}:role/${ROLE} \
-           --role-session-name ${ROLE}${$} \
-           --duration-seconds ${AWS_STS_DURATION_SECONDS:-3600} \
-           --serial-number ${MFA_ARN} \
-           --token-code ${aws_token} 2>/dev/null) || { echo "Error assuming role"; exit 1; }
+  if [[ "${use_mfa}" = "false" ]]; then
+    JSON=$(aws sts assume-role \
+             --role-arn arn:aws:iam::${ACCOUNT}:role/${ROLE} \
+             --role-session-name ${ROLE}${$} \
+             --duration-seconds ${AWS_STS_DURATION_SECONDS:-3600}
+             2>/dev/null) || { echo "Error assuming role"; exit 1; }
+  else
+    JSON=$(aws sts assume-role \
+             --role-arn arn:aws:iam::${ACCOUNT}:role/${ROLE} \
+             --role-session-name ${ROLE}${$} \
+             --duration-seconds ${AWS_STS_DURATION_SECONDS:-3600}
+             --serial-number ${MFA_ARN} \
+             --token-code ${aws_token} 2>/dev/null) || { echo "Error assuming role"; exit 1; }
+  fi
 
       AWS_ACCESS_KEY_ID=$(echo ${JSON} | jq --raw-output ".Credentials[\"AccessKeyId\"]")
   AWS_SECRET_ACCESS_KEY=$(echo ${JSON} | jq --raw-output ".Credentials[\"SecretAccessKey\"]")
@@ -144,7 +155,7 @@ GetAccountName() {
 
 PrintAccountInfo() {
   GetAccountInfo
-  
+
   echo "Account Name: ${aws_account}"
   echo "Account ID: ${ACCOUNT}"
   echo "Assumed Role: ${ROLE}"
